[project]
name = "code-civil-langchain"
version = "0.0.1"
description = "Agent RAG sur le code civil français"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy",
    "langchain",
    "python-dotenv",
    "docling",
    "langchain-openrouter",
    "langgraph",
    "chromadb",
    "torch",
    "torchvision",
    "torchaudio",
    "mistralai",
    "streamlit>=1.65.0",
]


[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }

[project.scripts]
code-civil-langchain = "code_civil_langchain:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.10.0",
    "jupyter>=1.1.1",
    "ruff>=0.16.10",
]