[project]
name = "code-civil-langchain"
version = "0.0.1"
description = "Agent RAG sur le code civil français"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "docling",
    "langchain",
    "python-dotenv",
    "langchain-openrouter",
    "langgraph",
    "chromadb",
    "mistralai",
    "streamlit>=1.65.0",
]

[project.scripts]
code-civil-langchain = "code_civil_langchain:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=26.10.0",
    "jupyter>=1.1.1",
    "ruff>=0.16.10",
]
